import { ArrowLeft, Pencil, Plus } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Button } from "@/components/ui/button";
import { AssignmentStatusBadge } from "@/modules/assignments";
import { PermissionGate } from "@/modules/authorization";
import { formatCpf, getWorkerOperationalDetail, workerIdSchema, WorkerStatusAction, WorkerStatusBadge } from "@/modules/workers";
import { isAppError, toPublicErrorMessage } from "@/shared/errors";

function formatDate(value: string | null): string { return value ? new Intl.DateTimeFormat("pt-BR", { timeZone: "UTC" }).format(new Date(`${value}T00:00:00Z`)) : "Em aberto"; }

export default async function WorkerDetailsPage({ params }: PageProps<"/app/workers/[workerId]">) {
  const route = workerIdSchema.safeParse((await params).workerId); if (!route.success) notFound();
  let detail; try { detail = await getWorkerOperationalDetail(route.data); } catch (error) { if (isAppError(error) && error.code === "NOT_FOUND") notFound(); return <main className="mx-auto max-w-5xl px-4 py-10"><p className="text-sm text-destructive">{toPublicErrorMessage(error)}</p></main>; }
  const { worker, assignments, activeAssignment } = detail;
  return <main className="mx-auto max-w-5xl px-4 py-10 sm:px-6 lg:px-8">
    <Button asChild variant="outline" size="sm"><Link href="/app/workers"><ArrowLeft className="size-4" />Voltar para colaboradores</Link></Button>
    <div className="mt-6 flex flex-col gap-5 sm:flex-row sm:justify-between"><div><div className="flex flex-wrap items-center gap-3"><h1 className="text-2xl font-semibold">{worker.full_name}</h1><WorkerStatusBadge status={worker.status} /></div><p className="mt-2 text-sm text-muted-foreground tabular-nums">{formatCpf(worker.document_number)}</p></div><PermissionGate permission="worker:update"><Button asChild variant="outline"><Link href={`/app/workers/${worker.id}/edit`}><Pencil className="size-4" />Editar</Link></Button></PermissionGate></div>
    <dl className="mt-6 grid gap-x-5 gap-y-4 rounded-lg border bg-card p-4 sm:grid-cols-2"><Detail label="E-mail" value={worker.email ?? "Não informado"} /><Detail label="Telefone" value={worker.phone ?? "Não informado"} /><Detail label="Início do vínculo" value={formatDate(worker.engagement_start_date)} /><Detail label="Fim do vínculo" value={formatDate(worker.engagement_end_date)} /></dl>
    <section className="mt-6 rounded-lg border bg-card"><div className="border-b px-5 py-4"><h2 className="font-semibold">Alocação atual</h2></div>{activeAssignment ? <div className="grid gap-4 px-5 py-5 sm:grid-cols-2"><Detail label="Cargo" value={activeAssignment.position.job_role.name} /><Detail label="Posto" value={activeAssignment.position.job_role.name} /><Detail label="Unidade" value={activeAssignment.position.unit.name} /><Detail label="Operação" value={activeAssignment.position.unit.operation.name} /><Detail label="Cliente" value={activeAssignment.position.unit.operation.contract.client.trade_name} /><Detail label="Período" value={`${formatDate(activeAssignment.start_date)} — ${formatDate(activeAssignment.end_date)}`} /><div className="sm:col-span-2 text-sm"><Link href={`/app/assignments/${activeAssignment.id}`} className="font-medium hover:underline">Ver alocação</Link><span className="mx-2 text-muted-foreground">·</span><Link href={`/app/units/${activeAssignment.position.unit.id}/positions/${activeAssignment.position.id}`} className="font-medium hover:underline">Ver posto</Link><span className="mx-2 text-muted-foreground">·</span><Link href={`/app/units/${activeAssignment.position.unit.id}`} className="font-medium hover:underline">Ver unidade</Link></div></div> : <p className="px-5 py-6 text-sm text-muted-foreground">Sem alocação ativa.</p>}</section>
    <section className="mt-6 rounded-lg border bg-card"><div className="flex items-center justify-between border-b px-5 py-4"><div><h2 className="font-semibold">Histórico de alocações</h2><p className="mt-1 text-sm text-muted-foreground">Mais recentes primeiro, incluindo todos os status.</p></div>{worker.status === "active" ? <PermissionGate permission="assignment:create"><Button asChild size="sm"><Link href={`/app/assignments/new?workerId=${worker.id}`}><Plus className="size-4" />Nova alocação</Link></Button></PermissionGate> : null}</div>{assignments.length === 0 ? <p className="px-5 py-6 text-sm text-muted-foreground">Nenhuma alocação relacionada.</p> : <ul className="divide-y">{assignments.map((assignment) => <li key={assignment.id} className="flex flex-col gap-3 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><Link href={`/app/assignments/${assignment.id}`} className="font-medium hover:underline">{assignment.position.job_role.name}</Link><p className="mt-1 text-sm text-muted-foreground"><Link href={`/app/units/${assignment.position.unit.id}`} className="hover:underline">{assignment.position.unit.name}</Link> · <Link href={`/app/operations/${assignment.position.unit.operation.id}`} className="hover:underline">{assignment.position.unit.operation.name}</Link> · {formatDate(assignment.start_date)} — {formatDate(assignment.end_date)}</p></div><AssignmentStatusBadge status={assignment.status} /></li>)}</ul>}</section>
    <PermissionGate permission="worker:update"><section className="mt-6 border-t pt-5"><WorkerStatusAction workerId={worker.id} currentStatus={worker.status} /></section></PermissionGate>
  </main>;
}
function Detail({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs font-medium uppercase tracking-wide text-muted-foreground">{label}</dt><dd className="mt-1 text-sm">{value}</dd></div>; }
