import { ArrowLeft, Pencil, Plus } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Button } from "@/components/ui/button";
import { AssignmentStatusBadge } from "@/modules/assignments";
import { PermissionGate } from "@/modules/authorization";
import { PositionStatusBadge } from "@/modules/positions";
import { getUnitOperationalDetail, UnitStatusAction, UnitStatusBadge, unitIdSchema } from "@/modules/units";
import { isAppError, toPublicErrorMessage } from "@/shared/errors";

function formatDate(value: string | null): string { return value ? new Intl.DateTimeFormat("pt-BR", { timeZone: "UTC" }).format(new Date(`${value}T00:00:00Z`)) : "Em aberto"; }

export default async function UnitDetailsPage({ params }: PageProps<"/app/units/[unitId]">) {
  const route = unitIdSchema.safeParse((await params).unitId); if (!route.success) notFound();
  let unit; try { unit = await getUnitOperationalDetail(route.data); } catch (error) { if (isAppError(error) && error.code === "NOT_FOUND") notFound(); return <main className="mx-auto max-w-5xl px-4 py-10"><p className="text-sm text-destructive">{toPublicErrorMessage(error)}</p></main>; }
  return <main className="mx-auto max-w-5xl px-4 py-10 sm:px-6 lg:px-8">
    <Button asChild variant="outline" size="sm"><Link href="/app/units"><ArrowLeft className="size-4" />Voltar para unidades</Link></Button>
    <div className="mt-6 flex flex-col gap-5 sm:flex-row sm:justify-between"><div><div className="flex items-center gap-3"><h1 className="text-2xl font-semibold">{unit.name}</h1><UnitStatusBadge status={unit.status} /></div><p className="mt-2 text-sm text-muted-foreground">Operação: <Link href={`/app/operations/${unit.operation.id}`} className="font-medium text-foreground hover:underline">{unit.operation.name}</Link> · Cliente: <Link href={`/app/clients/${unit.operation.contract.client.id}`} className="font-medium text-foreground hover:underline">{unit.operation.contract.client.trade_name}</Link></p></div><PermissionGate permission="unit:update"><Button asChild variant="outline"><Link href={`/app/units/${unit.id}/edit`}><Pencil className="size-4" />Editar</Link></Button></PermissionGate></div>
    <p className="mt-3 text-sm text-muted-foreground">{[unit.address, unit.city, unit.state].filter(Boolean).join(" · ") || "Localização não informada"} · {unit.timezone}</p>
    <dl className="mt-6 grid divide-y rounded-lg border bg-card sm:grid-cols-4 sm:divide-x sm:divide-y-0"><Metric label="Postos ativos" value={unit.summary.activePositions} /><Metric label="Cargos utilizados" value={unit.summary.usedJobRoles} /><Metric label="Efetivo base" value={unit.summary.baseRequiredHeadcount} /><Metric label="Ocupação atual" value={unit.summary.activeAssignments} /></dl>
    <section className="mt-6 rounded-lg border bg-card"><div className="flex items-center justify-between border-b px-5 py-4"><div><h2 className="font-semibold">Postos</h2><p className="mt-1 text-sm text-muted-foreground">Efetivo estrutural e ocupação atual.</p></div>{unit.status === "active" ? <PermissionGate permission="position:create"><Button asChild size="sm"><Link href={`/app/units/${unit.id}/positions/new`}><Plus className="size-4" />Novo posto</Link></Button></PermissionGate> : null}</div>{unit.positions.length === 0 ? <p className="px-5 py-6 text-sm text-muted-foreground">Esta unidade ainda não possui postos cadastrados.</p> : <div className="overflow-x-auto"><table className="min-w-[680px] w-full text-left text-sm"><thead className="border-b bg-muted/40 text-xs uppercase text-muted-foreground"><tr><th className="px-5 py-3">Cargo</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Efetivo base</th><th className="px-5 py-3">Ocupação</th><th className="px-5 py-3">Déficit</th></tr></thead><tbody className="divide-y">{unit.positions.map((position) => <tr key={position.id}><td className="px-5 py-4"><Link className="font-medium hover:underline" href={`/app/units/${unit.id}/positions/${position.id}`}>{position.job_role.name}</Link></td><td className="px-5 py-4"><PositionStatusBadge status={position.status} /></td><td className="px-5 py-4 tabular-nums">{position.base_required_headcount}</td><td className="px-5 py-4 tabular-nums"><span className="font-medium text-foreground">{position.activeAssignments}</span> de {position.base_required_headcount}</td><td className="px-5 py-4 tabular-nums">{position.deficit}</td></tr>)}</tbody></table></div>}</section>
    <section className="mt-6 rounded-lg border bg-card"><div className="border-b px-5 py-4"><h2 className="font-semibold">Colaboradores alocados</h2><p className="mt-1 text-sm text-muted-foreground">Somente alocações ativas nesta unidade.</p></div>{unit.allocatedWorkers.length === 0 ? <p className="px-5 py-6 text-sm text-muted-foreground">Não há colaboradores com alocação ativa nesta unidade.</p> : <ul className="divide-y">{unit.allocatedWorkers.map((assignment) => <li key={assignment.id} className="flex flex-col gap-2 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><Link className="font-medium hover:underline" href={`/app/workers/${assignment.worker.id}`}>{assignment.worker.full_name}</Link><p className="mt-1 text-sm text-muted-foreground">{assignment.position.job_role.name} · <Link href={`/app/units/${unit.id}/positions/${assignment.position.id}`} className="hover:underline">{assignment.position.job_role.name}</Link> · desde {formatDate(assignment.start_date)}</p></div><AssignmentStatusBadge status={assignment.status} /></li>)}</ul>}</section>
    <PermissionGate permission="unit:update"><section className="mt-6 border-t pt-5"><UnitStatusAction unitId={unit.id} currentStatus={unit.status} /></section></PermissionGate>
  </main>;
}
function Metric({ label, value }: { label: string; value: number }) { return <div className="p-4"><dt className="text-xs font-medium uppercase tracking-wide text-muted-foreground">{label}</dt><dd className="mt-1 text-xl font-semibold tabular-nums">{value}</dd></div>; }
