-- Phase 5C: coverage is an assignment reference; published schedules remain immutable.
create table public.replacements (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete restrict,
  absence_id uuid not null references public.absences(id) on delete restrict,
  replacement_assignment_id uuid not null references public.assignments(id) on delete restrict,
  status text not null default 'active', created_at timestamptz not null default now(),
  created_by uuid not null references public.profiles(id) on delete restrict, cancelled_at timestamptz, cancelled_by uuid references public.profiles(id) on delete restrict,
  constraint replacements_status_valid check (status in ('active','cancelled')),
  constraint replacements_lifecycle_valid check ((status = 'active' and cancelled_at is null and cancelled_by is null) or (status = 'cancelled' and cancelled_at is not null and cancelled_by is not null))
);
create unique index replacements_one_active_per_absence_idx on public.replacements(absence_id) where status = 'active';
create index replacements_active_assignment_idx on public.replacements(replacement_assignment_id) where status = 'active';
alter table public.replacements enable row level security;
create policy "Members with replacement read can read replacements" on public.replacements for select to authenticated using (public.has_organization_permission(organization_id, 'replacement:read'));
revoke all on table public.replacements from anon, authenticated; grant select on table public.replacements to authenticated;

-- Preserve the existing matrix and append only replacement permissions.
create or replace function public.has_organization_permission(target_organization_id uuid, required_permission text) returns boolean language sql stable security definer set search_path = '' as $$
 select exists (select 1 from public.organization_members m where m.organization_id=target_organization_id and m.profile_id=auth.uid() and m.status='active' and (
   (required_permission in ('replacement:read','replacement:create','replacement:cancel') and m.role in ('DIRECTOR','OPERATIONS_MANAGER','SUPERVISOR','HR'))
   or (required_permission='replacement:read' and m.role in ('RECRUITER','ADMINISTRATIVE'))
   or (required_permission not like 'replacement:%' and required_permission = any(case m.role
     when 'DIRECTOR' then array['client:read','client:create','client:update','contract:read','contract:create','contract:update','operation:read','operation:create','operation:update','unit:read','unit:create','unit:update','job_role:read','job_role:create','job_role:update','position:read','position:create','position:update','worker:read','worker:create','worker:update','assignment:read','assignment:create','assignment:update','schedule:read','schedule:create','schedule:update','schedule:submit','schedule:approve','schedule:publish','absence:read','absence:create','absence:cancel','organization_member:read','organization_member:update','audit:read']::text[]
     when 'OPERATIONS_MANAGER' then array['client:read','client:create','client:update','contract:read','contract:create','contract:update','operation:read','operation:create','operation:update','unit:read','unit:create','unit:update','job_role:read','job_role:create','job_role:update','position:read','position:create','position:update','worker:read','assignment:read','assignment:create','assignment:update','schedule:read','schedule:create','schedule:update','schedule:submit','schedule:approve','schedule:publish','absence:read','absence:create','absence:cancel']::text[]
     when 'SUPERVISOR' then array['client:read','contract:read','operation:read','unit:read','unit:update','job_role:read','position:read','position:update','worker:read','assignment:read','schedule:read','schedule:create','schedule:update','schedule:submit','schedule:approve','schedule:publish','absence:read','absence:create','absence:cancel']::text[]
     when 'HR' then array['client:read','contract:read','operation:read','unit:read','job_role:read','position:read','worker:read','worker:create','worker:update','assignment:read','assignment:update','schedule:read','schedule:create','schedule:update','schedule:submit','schedule:approve','schedule:publish','absence:read','absence:create','absence:cancel']::text[]
     when 'RECRUITER' then array['client:read','contract:read','operation:read','unit:read','job_role:read','position:read','worker:read','worker:create','assignment:read','schedule:read','absence:read']::text[]
     when 'ADMINISTRATIVE' then array['client:read','contract:read','operation:read','unit:read','job_role:read','position:read','worker:read','assignment:read','schedule:read','absence:read']::text[] else array[]::text[] end))));
$$;
revoke all on function public.has_organization_permission(uuid,text) from public; grant execute on function public.has_organization_permission(uuid,text) to authenticated;
alter table public.audit_events drop constraint audit_events_entity_type_valid; alter table public.audit_events add constraint audit_events_entity_type_valid check (entity_type in ('client','contract','operation','unit','position','worker','organization_member','assignment','job_role','schedule','schedule_revision','schedule_entry','absence','replacement'));

create or replace function private.replacement_context(aid uuid) returns table(org uuid, position_id uuid, absent_worker uuid, starts_at timestamptz, ends_at timestamptz, absence_status text) language sql stable security definer set search_path='' as $$ select a.organization_id,x.position_id,x.worker_id,e.starts_at,e.ends_at,a.status from public.absences a join public.schedule_entries e on e.id=a.schedule_entry_id join public.assignments x on x.id=e.assignment_id where a.id=aid $$;
create or replace function private.create_replacement(aid uuid, candidate_assignment uuid) returns public.replacements language plpgsql security definer set search_path='' as $$
declare c record; candidate record; item public.replacements; actor uuid:=auth.uid(); start_date date; end_date date;
begin
 perform 1 from public.absences where id=aid for update; if not found then raise exception 'Absence not found' using errcode='P0002'; end if;
 select * into c from private.replacement_context(aid); if c.absence_status <> 'reported' then raise exception 'Only a reported Absence can be replaced' using errcode='23514'; end if;
 if exists(select 1 from public.replacements where absence_id=aid and status='active') then raise exception 'Absence already has an active Replacement' using errcode='23505'; end if;
 select x.worker_id,x.position_id,x.status,x.start_date,x.end_date,w.organization_id,w.status worker_status,u.timezone into candidate from public.assignments x join public.workers w on w.id=x.worker_id join public.positions p on p.id=x.position_id join public.units u on u.id=p.unit_id where x.id=candidate_assignment;
 if not found then raise exception 'Assignment not found' using errcode='P0002'; end if;
 if candidate.organization_id<>c.org or candidate.position_id<>c.position_id or candidate.worker_id=c.absent_worker or candidate.status not in ('pending','active') or candidate.worker_status<>'active' then raise exception 'Replacement Assignment is not eligible' using errcode='23514'; end if;
 start_date := (c.starts_at at time zone candidate.timezone)::date; end_date := ((c.ends_at-interval '1 microsecond') at time zone candidate.timezone)::date;
 if start_date<candidate.start_date or (candidate.end_date is not null and end_date>candidate.end_date) then raise exception 'Replacement Assignment does not cover the ScheduleEntry interval' using errcode='23514'; end if;
 if exists(select 1 from public.schedule_entries e join public.assignments x on x.id=e.assignment_id join public.schedule_revisions r on r.id=e.schedule_revision_id join public.schedules s on s.id=r.schedule_id where x.worker_id=candidate.worker_id and s.organization_id=c.org and (r.status in ('pending_approval','approved') or r.status='published') and tstzrange(e.starts_at,e.ends_at,'[)') && tstzrange(c.starts_at,c.ends_at,'[)')) or exists(select 1 from public.replacements z join public.absences a on a.id=z.absence_id join public.schedule_entries e on e.id=a.schedule_entry_id join public.assignments x on x.id=z.replacement_assignment_id where z.status='active' and z.organization_id=c.org and x.worker_id=candidate.worker_id and tstzrange(e.starts_at,e.ends_at,'[)') && tstzrange(c.starts_at,c.ends_at,'[)')) then raise exception 'Replacement Worker has a conflict' using errcode='23P01'; end if;
 insert into public.replacements(organization_id,absence_id,replacement_assignment_id,created_by) values(c.org,aid,candidate_assignment,actor) returning * into item;
 insert into public.audit_events(organization_id,actor_user_id,entity_type,entity_id,action,metadata) values(item.organization_id,actor,'replacement',item.id,'create',jsonb_build_object('previous_state','{}'::jsonb,'new_state',jsonb_build_object('absence_id',item.absence_id,'replacement_assignment_id',item.replacement_assignment_id),'changes',jsonb_build_array('absence_id','replacement_assignment_id'))); return item;
end $$;
create or replace function public.create_replacement(organization_id uuid, absence_id uuid, assignment_id uuid) returns public.replacements language plpgsql security definer set search_path='' as $$ begin perform private.require_organization_permission(create_replacement.organization_id,'replacement:create'); if not exists(select 1 from public.absences a where a.id=create_replacement.absence_id and a.organization_id=create_replacement.organization_id) then raise exception 'Absence belongs to another Organization' using errcode='23514'; end if; return private.create_replacement(create_replacement.absence_id,create_replacement.assignment_id); end $$;
create or replace function private.cancel_replacement(rid uuid) returns public.replacements language plpgsql security definer set search_path='' as $$ declare old public.replacements; item public.replacements; actor uuid:=auth.uid(); begin select * into old from public.replacements where id=rid for update; if not found then raise exception 'Replacement not found' using errcode='P0002'; end if; if old.status<>'active' then raise exception 'Only an active Replacement can be cancelled' using errcode='23514'; end if; update public.replacements set status='cancelled',cancelled_at=now(),cancelled_by=actor where id=rid returning * into item; insert into public.audit_events(organization_id,actor_user_id,entity_type,entity_id,action,metadata) values(item.organization_id,actor,'replacement',item.id,'cancel',public.build_audit_metadata(to_jsonb(old),to_jsonb(item),array['status','cancelled_at','cancelled_by']::text[],array['status','cancelled_at','cancelled_by']::text[])); return item; end $$;
create or replace function public.cancel_replacement(organization_id uuid,replacement_id uuid) returns public.replacements language plpgsql security definer set search_path='' as $$ begin perform private.require_organization_permission(cancel_replacement.organization_id,'replacement:cancel'); if not exists(select 1 from public.replacements r where r.id=cancel_replacement.replacement_id and r.organization_id=cancel_replacement.organization_id) then raise exception 'Replacement belongs to another Organization' using errcode='23514'; end if; return private.cancel_replacement(cancel_replacement.replacement_id); end $$;
create or replace function public.list_replacement_candidates(organization_id uuid,absence_id uuid) returns table(assignment_id uuid,worker_id uuid,worker_full_name text) language sql security definer set search_path='' as $$ select x.id,w.id,w.full_name from private.replacement_context(absence_id) c join public.assignments x on x.position_id=c.position_id join public.workers w on w.id=x.worker_id where public.has_organization_permission(list_replacement_candidates.organization_id,'replacement:create') and c.org=list_replacement_candidates.organization_id and c.absence_status='reported' and x.status in ('pending','active') and w.status='active' and w.id<>c.absent_worker and not exists(select 1 from public.replacements z join public.absences a on a.id=z.absence_id join public.schedule_entries e on e.id=a.schedule_entry_id join public.assignments rx on rx.id=z.replacement_assignment_id where z.status='active' and rx.worker_id=w.id and tstzrange(e.starts_at,e.ends_at,'[)') && tstzrange(c.starts_at,c.ends_at,'[)')) order by w.full_name $$;
revoke all on function private.replacement_context(uuid),private.create_replacement(uuid,uuid),private.cancel_replacement(uuid) from public,anon,authenticated; revoke all on function public.create_replacement(uuid,uuid,uuid),public.cancel_replacement(uuid,uuid),public.list_replacement_candidates(uuid,uuid) from anon; grant execute on function public.create_replacement(uuid,uuid,uuid),public.cancel_replacement(uuid,uuid),public.list_replacement_candidates(uuid,uuid) to authenticated;
